name: 3. Deploy to Dev

on:
  workflow_run:
    workflows: ["2. Build, Package, & Publish"]
    types: [completed]
    branches: [main]

jobs:
  deploy-to-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: 'Dev'
      app-name: 'app-maaldocomapi-dev-cus'
    secrets:
      publish-profile: ${{ secrets.AZURE_DEV_WEBAPP_PUBLISH_PROFILE }}

#      - name: Run EF migrations
#        run: ./efbundle --connection ${{ secrets.AZURE_DEV_MIGRATIONS_CONNECTION_STRING }} --verbose