name: 3. Deploy to Dev

on:
  workflow_run:
    workflows: ["2. Build, Package, & Publish"]
    types: [completed]
    branches: [main]

jobs:
  deploy-to-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: 'Dev'
      app-name: 'app-maaldocomapi-dev-cus'
      workflow-run-id: ${{ github.event.workflow_run.id }}
    secrets:
      publish-profile: ${{ secrets.AZURE_DEV_WEBAPP_PUBLISH_PROFILE }}
      migrations-connection-string: ${{ secrets.AZURE_DEV_MIGRATIONS_CONNECTION_STRING }}