name: 4. Deploy to Test

on:
  workflow_dispatch:

jobs:
  deploy-to-test:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: 'Test'
      app-name: 'app-maaldocomapi-tst-cus'
    secrets:
      publish-profile: ${{ secrets.AZURE_TST_WEBAPP_PUBLISH_PROFILE }}