name: 5. Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: 'Prod'
      app-name: 'app-maaldocomapi-prd-cus'
    secrets:
      publish-profile: ${{ secrets.AZURE_PRD_WEBAPP_PUBLISH_PROFILE }}